# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgtctl < Formula
  desc ""
  homepage ""
  version "1.0.0-rc5"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/1.0.0-rc5/lgtctl_1.0.0-rc5_darwin_amd64.tar.gz"
      sha256 "523e04213ff8c7c4986d96b54f83abc470ddd4fea9e4836f48a6b76a0401cd6d"

      def install
        bin.install "lgtctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/1.0.0-rc5/lgtctl_1.0.0-rc5_darwin_arm64.tar.gz"
      sha256 "30673fbb3c85b8117fa4cad02085ff0efd9d18dc6f07e2402a2b4402d3649933"

      def install
        bin.install "lgtctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/1.0.0-rc5/lgtctl_1.0.0-rc5_linux_amd64.tar.gz"
      sha256 "c4d62c299e25138bb81e2370e89f53f72a61077c294c56f628f489697c9d5585"
      def install
        bin.install "lgtctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/1.0.0-rc5/lgtctl_1.0.0-rc5_linux_arm64.tar.gz"
      sha256 "0654fed8568d07e3ac2332a455f7e7500ef99098f33a61a1cfa189b71ffe0e61"
      def install
        bin.install "lgtctl"
      end
    end
  end
end
