# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgtctl < Formula
  desc ""
  homepage ""
  version "1.2.0"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/v1.2.0/lgtctl_1.2.0_darwin_amd64.tar.gz"
      sha256 "aa0ea8fba3638016e04ba2e364613c2f7a22d2cbbfdf5873d7bf80421a1d56fd"

      define_method(:install) do
        bin.install "lgtctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/v1.2.0/lgtctl_1.2.0_darwin_arm64.tar.gz"
      sha256 "ed28dcdf9d17fb50dc368ec30aa4cf7e670ad31aa44b073fad6753d512730f63"

      define_method(:install) do
        bin.install "lgtctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/v1.2.0/lgtctl_1.2.0_linux_amd64.tar.gz"
      sha256 "54f6e0497d2e74ed72b0c8cae83fbb2c797bde90419f22cff862121eed32df7c"
      define_method(:install) do
        bin.install "lgtctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgtnimbus/lgtctl/releases/download/v1.2.0/lgtctl_1.2.0_linux_arm64.tar.gz"
      sha256 "d3aa77b80dd1b92a7ccf2825c77d91044316bf06e2cf8d71f88d145d1fb3e748"
      define_method(:install) do
        bin.install "lgtctl"
      end
    end
  end
end
